# https://niv-backend.herokuapp.com
http://localhost:3000
-i
-s
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdXN0dWJoIiwiaW5zdGl0dXRlIjoianNwbSIsImRlc2lnbmF0aW9uIjoiYWRtaW4iLCJpYXQiOjE2Mjg2NzEzMzN9.JIFCIyXnb6NO1cgeMpNK-aD2x3b_Jjmlk9OxSgnhIoc
--

--
GET /

--
GET /node

--
POST /user/register
{
	"username": "kaustubh",
	"password": "kaustubh",
	"email": "kaustubh.murumkar@gmail.com",
	"institute": "jspm",
	"designation": "admin"
}

--
POST /user/register
{
	"username": "sbmohite",
	"password": "admin123",
	"email": "sbmohite@gmail.com",
	"institute": "jspm",
	"designation": "admin"
}

--
POST /user/login
{
  "username": "sbmohite",
  "password": "admin"
}

--
POST /user/login
{
  "username": "kaustubh",
  "password": "kasdlsaustubh"
}

--
POST /node/add
{
  "uid": "100000",
  "location": "lab1",
  "machineName": "freezer",
  "isTemp": true,
  "isCO2": false,
  "isHum": false,
  "temperatureRange": {
    "min": 40,
    "max": 80
  }
}


--
DELETE /node/100000

--
POST /write/reading
{
  "uid": "100001",
  "temperature": "24",
  "humidity": "12",
  "battery": "20",
  "user": "kaustubh"
}

--
POST /write/reading
{
  "uid": "100001",
  "co2": "5.1",
  "battery": "20",
  "user": "kaustubh"
}

--
POST /write/reading
{
  "uid": "100003",
  "temperature": "60.6",
  "humidity": "69",
  "co2": "69.0",
  "pressure": "69",
  "user": "kaustubh",
  "backup": "1",
  "datetime": "1629402407"
}

--
GET /node/readings/100003

--
GET /node/readings/all/100001

--
GET /user/about

--
GET /node/getcsv/100001

--
GET /write/setpoints/100000

--
GET /user/allusers
