# https://niv-backend.herokuapp.com
http://localhost:3000
-i
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdXN0dWJoIiwiaW5zdGl0dXRlIjoianNwbSIsImRlc2lnbmF0aW9uIjoiYWRtaW4iLCJpYXQiOjE2MjAzMDM3NjV9.YHyPBDi8rtAUwUg9HN9y8ke3aNkApfopJ1t9mOxkHIY
--

--
GET /

--
GET /node

--
POST /user/register
{
	"username": "kaustubh",
	"password": "kaustubh",
	"email": "kaustubh.murumkar@gmail.com",
	"institute": "jspm",
	"designation": "admin"
}

--
POST /user/register
{
	"username": "sbmohite",
	"password": "admin123",
	"email": "sbmohite@gmail.com",
	"institute": "jspm",
	"designation": "admin"
}

--
POST /user/login
{
  "username": "kaustubh",
  "password": "kaustubh"
}

--
POST /user/login
{
  "username": "kaustubh",
  "password": "kasdlsaustubh"
}

--
POST /node/add
{
  "uid": "100000",
  "location": "lab1",
  "machineName": "freezer"
}


--
DELETE /node/100000

--
POST /write/reading
{
  "uid": "100002",
  "temperature": "29.22",
  "humidity": "-59",
  "co2": "0.5",
  "pressure": "11",
  "battery": "19",
  "user": "kaustubh"
}

--
POST /write/reading
{
  "uid": "100001",
  "temperature": "30.6",
  "humidity": "5",
  "co2": "18.0",
  "pressure": "9",
  "user": "kaustubh",
  "backup": "1",
  "datetime": "1623718150"
}

--
GET /node/readings/100000

--
GET /node/readings/all/100001

--
GET /user/about

--
GET /node/getcsv/100001
