http://localhost:3000
-i
Accept: */*
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthdXN0dWJoIiwiaW5zdGl0dXRlIjoianNwbSIsImRlc2lnbmF0aW9uIjoiYWRtaW4iLCJpYXQiOjE2MTUyMTMyNzB9.clAP0bldNFYS53nKN0BIHOCp6FRJ8pU1ltgyCfn9l3c
--

--
GET /

--
GET /node

--
POST /user/register
{
	"username": "kaustubh",
	"password": "kaustubh",
	"email": "kaustubh.murumkar@gmail.com",
	"institute": "jspm",
	"designation": "admin"
}

--
POST /user/login
{
  "username": "kaustubh",
  "password": "kaustubh"
}

--
POST /user/login
{
  "username": "kaustubh",
  "password": "kasdlsaustubh"
}

--
POST /node/add
{
  "uid": "100001",
  "location": "jspm",
  "machineName": "heater"
}


--
DELETE /node/100000

--
POST /write/reading
{
  "uid": "100002",
  "temperature": "27.6", 
  "humidity": "59",
  "co2": "0.5",
  "pressure": "11",
  "user": "kaustubh",
  "datetime": 1616234853
}

--
POST /write/reading
{
  "uid": "100002",
  "temperature": "30.6",
  "humidity": "5",
  "co2": "18.0",
  "pressure": "9",
  "user": "kaustubh",
  "backup": "1",
  "datetime": 1616234853
}

--
GET /node/readings/100000

--
GET /node/readings/all/100000
